
use db_session2;
CREATE TABLE student(
MSV INT PRIMARY KEY,
TenSV VARCHAR(50) NOT NULL
);
CREATE TABLE Subject(
MaMH INT PRIMARY KEY,
TenMH VARCHAR(50) NOT NULL,
TinChi INT NOT NULL CHECK(TinChi >0) 
);