

CREATE TABLE Subject(
MaMH INT PRIMARY KEY,
TenMH VARCHAR(50) NOT NULL,
TinChi INT NOT NULL CHECK(TinChi >0) 
);
ALTER TABLE Subject
ADD MaGV INT;


CREATE TABLE Teacher (
    MaGV INT PRIMARY KEY,          
    TenGV VARCHAR(50) NOT NULL,    
    Email VARCHAR(100) UNIQUE
);

ALTER TABLE Subject
ADD CONSTRAINT FK_Subject_Teacher
FOREIGN KEY (MaGV)
REFERENCES Teacher(MaGV);

